import EnrollmentRequest from '../Models/enrollmentRequestModel.js';
import Course from '../Models/courseModel.js';
import { logActivity } from '../Middleware/activityLogger.js';

// ── POST /api/enrollments ──────────────────────────────────────────────────────
// Authenticated user requests enrollment in a course.
// userId and uniqueKey are NEVER taken from the request body.
export const requestEnrollment = async (req, res, next) => {
  try {
    const { courseId } = req.body;

    if (!courseId) {
      return res.status(400).json({
        status:  'error',
        code:    'VALIDATION_ERROR',
        message: 'courseId is required.',
      });
    }

    // Confirm the course actually exists
    const course = await Course.findById(courseId);
    if (!course) {
      return res.status(404).json({
        status:  'error',
        code:    'NOT_FOUND',
        message: 'Course not found.',
      });
    }

    // Check for an existing request (any status)
    const existing = await EnrollmentRequest.findOne({
      userId:   req.user._id,
      courseId,
    });

    if (existing) {
      return res.status(409).json({
        status:  'error',
        code:    'DUPLICATE_REQUEST',
        message: `An enrollment request for this course already exists (status: ${existing.status}).`,
        data:    existing,
      });
    }

    // uniqueKey is generated by the pre-validate hook on the model
    const enrollment = await EnrollmentRequest.create({
      userId:   req.user._id,
      courseId,
    });

    logActivity({
      userId:   req.user._id,
      action:   'enrollment_request',
      metadata: { courseId, enrollmentId: enrollment._id },
    });

    return res.status(201).json({
      status:  'success',
      message: 'Enrollment request submitted.',
      data:    enrollment,
    });
  } catch (err) {
    // Mongoose duplicate key error (compound index race condition)
    if (err.code === 11000) {
      return res.status(409).json({
        status:  'error',
        code:    'DUPLICATE_REQUEST',
        message: 'You have already submitted an enrollment request for this course.',
      });
    }
    next(err);
  }
};

// ── GET /api/enrollments/me ────────────────────────────────────────────────────
export const getMyEnrollments = async (req, res, next) => {
  try {
    const enrollments = await EnrollmentRequest.find({ userId: req.user._id })
      .populate('courseId', 'courseCode courseName semesterId')
      .sort({ createdAt: -1 });

    return res.status(200).json({
      status: 'success',
      count:  enrollments.length,
      data:   enrollments,
    });
  } catch (err) {
    next(err);
  }
};
